#!/bin/sh
## Runs a tent-pole console script from the tent-pole checkout at
## {checkout}, preserving the caller's working directory. Generated by
## `tent-pole init --tent-pole-dev`. TENT_POLE can pass the tool as $1
## (it's invoked as a command prefix -- $(TENT_POLE) pkg-dir), but
## pandoc's --filter=X execs X directly with no shell in between, so a
## filter can't take an argument that way -- canvas-filter.sh/
## code-include-filter.sh/include-deps-filter.sh are symlinks to this
## same script instead, which picks the tool up from its own invoked
## name.
NAME=$(basename "$0" .sh)
if [ "$NAME" = "{impl_name}" ]; then
    TOOL=$1
    shift
else
    TOOL=$NAME
fi
DIR=$(pwd)
cd {checkout} || exit 1
poetry run sh -c 'cd "$1"; shift; tool=$1; shift; exec "$tool" "$@"' sh "$DIR" "$TOOL" "$@"
